/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ChangePasswordImport } from './routes/change-password'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as authRouteImport } from './routes/(auth)/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as authResetPasswordImport } from './routes/(auth)/reset-password'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as AuthenticatedUsersIndexImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedServicesIndexImport } from './routes/_authenticated/services/index'
import { Route as AuthenticatedRolesIndexImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedProjectsIndexImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedJournalEntriesIndexImport } from './routes/_authenticated/journal-entries/index'
import { Route as AuthenticatedInvoicesIndexImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedExpensesIndexImport } from './routes/_authenticated/expenses/index'
import { Route as AuthenticatedClientsIndexImport } from './routes/_authenticated/clients/index'
import { Route as AuthenticatedChartOfAccountsIndexImport } from './routes/_authenticated/chart-of-accounts/index'
import { Route as authForgotPasswordIndexImport } from './routes/(auth)/forgot-password/index'
import { Route as AuthenticatedUsersNewImport } from './routes/_authenticated/users/new'
import { Route as AuthenticatedServicesNewImport } from './routes/_authenticated/services/new'
import { Route as AuthenticatedRolesNewImport } from './routes/_authenticated/roles/new'
import { Route as AuthenticatedReportsOutstandingInvoicesImport } from './routes/_authenticated/reports/outstanding-invoices'
import { Route as AuthenticatedReportsInvoiceStatusImport } from './routes/_authenticated/reports/invoice-status'
import { Route as AuthenticatedReportsExpensesReportImport } from './routes/_authenticated/reports/expenses-report'
import { Route as AuthenticatedReportsCollectedPaymentsImport } from './routes/_authenticated/reports/collected-payments'
import { Route as AuthenticatedReportsClientStatementImport } from './routes/_authenticated/reports/client-statement'
import { Route as AuthenticatedProjectsNewImport } from './routes/_authenticated/projects/new'
import { Route as AuthenticatedProfilePasswordImport } from './routes/_authenticated/profile/password'
import { Route as AuthenticatedInvoicesNewImport } from './routes/_authenticated/invoices/new'
import { Route as AuthenticatedExpensesNewImport } from './routes/_authenticated/expenses/new'
import { Route as AuthenticatedClientsNewImport } from './routes/_authenticated/clients/new'
import { Route as AuthenticatedChartOfAccountsNewImport } from './routes/_authenticated/chart-of-accounts/new'
import { Route as authForgotPasswordResetCodeImport } from './routes/(auth)/forgot-password/reset-code'
import { Route as AuthenticatedReportsIncomeStatementIndexImport } from './routes/_authenticated/reports/income-statement/index'
import { Route as AuthenticatedInvoicesPaymentsIndexImport } from './routes/_authenticated/invoices/payments/index'
import { Route as AuthenticatedUsersUserIdEditImport } from './routes/_authenticated/users/$userId.edit'
import { Route as AuthenticatedServicesServiceIdEditImport } from './routes/_authenticated/services/$serviceId.edit'
import { Route as AuthenticatedRolesRoleIdEditImport } from './routes/_authenticated/roles/$roleId.edit'
import { Route as AuthenticatedReportsIncomeStatementRevenueDetailedImport } from './routes/_authenticated/reports/income-statement/revenue-detailed'
import { Route as AuthenticatedReportsIncomeStatementExpenseDetailedImport } from './routes/_authenticated/reports/income-statement/expense-detailed'
import { Route as AuthenticatedProjectsProjectIdEditImport } from './routes/_authenticated/projects/$projectId.edit'
import { Route as AuthenticatedInvoicesPaymentsNewImport } from './routes/_authenticated/invoices/payments/new'
import { Route as AuthenticatedInvoicesInvoiceIdPrintImport } from './routes/_authenticated/invoices/$invoiceId.print'
import { Route as AuthenticatedInvoicesInvoiceIdEditImport } from './routes/_authenticated/invoices/$invoiceId.edit'
import { Route as AuthenticatedExpensesExpenseIdEditImport } from './routes/_authenticated/expenses/$expenseId.edit'
import { Route as AuthenticatedClientsClientIdEditImport } from './routes/_authenticated/clients/$clientId.edit'
import { Route as AuthenticatedChartOfAccountsAccountIdEditImport } from './routes/_authenticated/chart-of-accounts/$accountId.edit'
import { Route as AuthenticatedInvoicesPaymentsPaymentIdEditImport } from './routes/_authenticated/invoices/payments/$paymentId.edit'

// Create/Update Routes

const ChangePasswordRoute = ChangePasswordImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const authRouteRoute = authRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const authResetPasswordRoute = authResetPasswordImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)

const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedServicesIndexRoute = AuthenticatedServicesIndexImport.update(
  {
    id: '/services/',
    path: '/services/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProjectsIndexRoute = AuthenticatedProjectsIndexImport.update(
  {
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedJournalEntriesIndexRoute =
  AuthenticatedJournalEntriesIndexImport.update({
    id: '/journal-entries/',
    path: '/journal-entries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInvoicesIndexRoute = AuthenticatedInvoicesIndexImport.update(
  {
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedExpensesIndexRoute = AuthenticatedExpensesIndexImport.update(
  {
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedClientsIndexRoute = AuthenticatedClientsIndexImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedChartOfAccountsIndexRoute =
  AuthenticatedChartOfAccountsIndexImport.update({
    id: '/chart-of-accounts/',
    path: '/chart-of-accounts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const authForgotPasswordIndexRoute = authForgotPasswordIndexImport.update({
  id: '/forgot-password/',
  path: '/forgot-password/',
  getParentRoute: () => authRouteRoute,
} as any)

const AuthenticatedUsersNewRoute = AuthenticatedUsersNewImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedServicesNewRoute = AuthenticatedServicesNewImport.update({
  id: '/services/new',
  path: '/services/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedRolesNewRoute = AuthenticatedRolesNewImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedReportsOutstandingInvoicesRoute =
  AuthenticatedReportsOutstandingInvoicesImport.update({
    id: '/reports/outstanding-invoices',
    path: '/reports/outstanding-invoices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedReportsInvoiceStatusRoute =
  AuthenticatedReportsInvoiceStatusImport.update({
    id: '/reports/invoice-status',
    path: '/reports/invoice-status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedReportsExpensesReportRoute =
  AuthenticatedReportsExpensesReportImport.update({
    id: '/reports/expenses-report',
    path: '/reports/expenses-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedReportsCollectedPaymentsRoute =
  AuthenticatedReportsCollectedPaymentsImport.update({
    id: '/reports/collected-payments',
    path: '/reports/collected-payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedReportsClientStatementRoute =
  AuthenticatedReportsClientStatementImport.update({
    id: '/reports/client-statement',
    path: '/reports/client-statement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProjectsNewRoute = AuthenticatedProjectsNewImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfilePasswordRoute =
  AuthenticatedProfilePasswordImport.update({
    id: '/profile/password',
    path: '/profile/password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInvoicesNewRoute = AuthenticatedInvoicesNewImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedExpensesNewRoute = AuthenticatedExpensesNewImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedClientsNewRoute = AuthenticatedClientsNewImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedChartOfAccountsNewRoute =
  AuthenticatedChartOfAccountsNewImport.update({
    id: '/chart-of-accounts/new',
    path: '/chart-of-accounts/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const authForgotPasswordResetCodeRoute =
  authForgotPasswordResetCodeImport.update({
    id: '/forgot-password/reset-code',
    path: '/forgot-password/reset-code',
    getParentRoute: () => authRouteRoute,
  } as any)

const AuthenticatedReportsIncomeStatementIndexRoute =
  AuthenticatedReportsIncomeStatementIndexImport.update({
    id: '/reports/income-statement/',
    path: '/reports/income-statement/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInvoicesPaymentsIndexRoute =
  AuthenticatedInvoicesPaymentsIndexImport.update({
    id: '/invoices/payments/',
    path: '/invoices/payments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedUsersUserIdEditRoute =
  AuthenticatedUsersUserIdEditImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedServicesServiceIdEditRoute =
  AuthenticatedServicesServiceIdEditImport.update({
    id: '/services/$serviceId/edit',
    path: '/services/$serviceId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedRolesRoleIdEditRoute =
  AuthenticatedRolesRoleIdEditImport.update({
    id: '/roles/$roleId/edit',
    path: '/roles/$roleId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedReportsIncomeStatementRevenueDetailedRoute =
  AuthenticatedReportsIncomeStatementRevenueDetailedImport.update({
    id: '/reports/income-statement/revenue-detailed',
    path: '/reports/income-statement/revenue-detailed',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedReportsIncomeStatementExpenseDetailedRoute =
  AuthenticatedReportsIncomeStatementExpenseDetailedImport.update({
    id: '/reports/income-statement/expense-detailed',
    path: '/reports/income-statement/expense-detailed',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedProjectsProjectIdEditRoute =
  AuthenticatedProjectsProjectIdEditImport.update({
    id: '/projects/$projectId/edit',
    path: '/projects/$projectId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInvoicesPaymentsNewRoute =
  AuthenticatedInvoicesPaymentsNewImport.update({
    id: '/invoices/payments/new',
    path: '/invoices/payments/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInvoicesInvoiceIdPrintRoute =
  AuthenticatedInvoicesInvoiceIdPrintImport.update({
    id: '/invoices/$invoiceId/print',
    path: '/invoices/$invoiceId/print',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInvoicesInvoiceIdEditRoute =
  AuthenticatedInvoicesInvoiceIdEditImport.update({
    id: '/invoices/$invoiceId/edit',
    path: '/invoices/$invoiceId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedExpensesExpenseIdEditRoute =
  AuthenticatedExpensesExpenseIdEditImport.update({
    id: '/expenses/$expenseId/edit',
    path: '/expenses/$expenseId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedClientsClientIdEditRoute =
  AuthenticatedClientsClientIdEditImport.update({
    id: '/clients/$clientId/edit',
    path: '/clients/$clientId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedChartOfAccountsAccountIdEditRoute =
  AuthenticatedChartOfAccountsAccountIdEditImport.update({
    id: '/chart-of-accounts/$accountId/edit',
    path: '/chart-of-accounts/$accountId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedInvoicesPaymentsPaymentIdEditRoute =
  AuthenticatedInvoicesPaymentsPaymentIdEditImport.update({
    id: '/invoices/payments/$paymentId/edit',
    path: '/invoices/payments/$paymentId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof authRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordImport
      parentRoute: typeof authRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/(auth)/forgot-password/reset-code': {
      id: '/(auth)/forgot-password/reset-code'
      path: '/forgot-password/reset-code'
      fullPath: '/forgot-password/reset-code'
      preLoaderRoute: typeof authForgotPasswordResetCodeImport
      parentRoute: typeof authRouteImport
    }
    '/_authenticated/chart-of-accounts/new': {
      id: '/_authenticated/chart-of-accounts/new'
      path: '/chart-of-accounts/new'
      fullPath: '/chart-of-accounts/new'
      preLoaderRoute: typeof AuthenticatedChartOfAccountsNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/expenses/new': {
      id: '/_authenticated/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AuthenticatedExpensesNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile/password': {
      id: '/_authenticated/profile/password'
      path: '/profile/password'
      fullPath: '/profile/password'
      preLoaderRoute: typeof AuthenticatedProfilePasswordImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/reports/client-statement': {
      id: '/_authenticated/reports/client-statement'
      path: '/reports/client-statement'
      fullPath: '/reports/client-statement'
      preLoaderRoute: typeof AuthenticatedReportsClientStatementImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/reports/collected-payments': {
      id: '/_authenticated/reports/collected-payments'
      path: '/reports/collected-payments'
      fullPath: '/reports/collected-payments'
      preLoaderRoute: typeof AuthenticatedReportsCollectedPaymentsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/reports/expenses-report': {
      id: '/_authenticated/reports/expenses-report'
      path: '/reports/expenses-report'
      fullPath: '/reports/expenses-report'
      preLoaderRoute: typeof AuthenticatedReportsExpensesReportImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/reports/invoice-status': {
      id: '/_authenticated/reports/invoice-status'
      path: '/reports/invoice-status'
      fullPath: '/reports/invoice-status'
      preLoaderRoute: typeof AuthenticatedReportsInvoiceStatusImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/reports/outstanding-invoices': {
      id: '/_authenticated/reports/outstanding-invoices'
      path: '/reports/outstanding-invoices'
      fullPath: '/reports/outstanding-invoices'
      preLoaderRoute: typeof AuthenticatedReportsOutstandingInvoicesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/roles/new': {
      id: '/_authenticated/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof AuthenticatedRolesNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/services/new': {
      id: '/_authenticated/services/new'
      path: '/services/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof AuthenticatedServicesNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/(auth)/forgot-password/': {
      id: '/(auth)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordIndexImport
      parentRoute: typeof authRouteImport
    }
    '/_authenticated/chart-of-accounts/': {
      id: '/_authenticated/chart-of-accounts/'
      path: '/chart-of-accounts'
      fullPath: '/chart-of-accounts'
      preLoaderRoute: typeof AuthenticatedChartOfAccountsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/expenses/': {
      id: '/_authenticated/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/journal-entries/': {
      id: '/_authenticated/journal-entries/'
      path: '/journal-entries'
      fullPath: '/journal-entries'
      preLoaderRoute: typeof AuthenticatedJournalEntriesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/services/': {
      id: '/_authenticated/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/chart-of-accounts/$accountId/edit': {
      id: '/_authenticated/chart-of-accounts/$accountId/edit'
      path: '/chart-of-accounts/$accountId/edit'
      fullPath: '/chart-of-accounts/$accountId/edit'
      preLoaderRoute: typeof AuthenticatedChartOfAccountsAccountIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/clients/$clientId/edit': {
      id: '/_authenticated/clients/$clientId/edit'
      path: '/clients/$clientId/edit'
      fullPath: '/clients/$clientId/edit'
      preLoaderRoute: typeof AuthenticatedClientsClientIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/expenses/$expenseId/edit': {
      id: '/_authenticated/expenses/$expenseId/edit'
      path: '/expenses/$expenseId/edit'
      fullPath: '/expenses/$expenseId/edit'
      preLoaderRoute: typeof AuthenticatedExpensesExpenseIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/invoices/$invoiceId/edit': {
      id: '/_authenticated/invoices/$invoiceId/edit'
      path: '/invoices/$invoiceId/edit'
      fullPath: '/invoices/$invoiceId/edit'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/invoices/$invoiceId/print': {
      id: '/_authenticated/invoices/$invoiceId/print'
      path: '/invoices/$invoiceId/print'
      fullPath: '/invoices/$invoiceId/print'
      preLoaderRoute: typeof AuthenticatedInvoicesInvoiceIdPrintImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/invoices/payments/new': {
      id: '/_authenticated/invoices/payments/new'
      path: '/invoices/payments/new'
      fullPath: '/invoices/payments/new'
      preLoaderRoute: typeof AuthenticatedInvoicesPaymentsNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/projects/$projectId/edit': {
      id: '/_authenticated/projects/$projectId/edit'
      path: '/projects/$projectId/edit'
      fullPath: '/projects/$projectId/edit'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/reports/income-statement/expense-detailed': {
      id: '/_authenticated/reports/income-statement/expense-detailed'
      path: '/reports/income-statement/expense-detailed'
      fullPath: '/reports/income-statement/expense-detailed'
      preLoaderRoute: typeof AuthenticatedReportsIncomeStatementExpenseDetailedImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/reports/income-statement/revenue-detailed': {
      id: '/_authenticated/reports/income-statement/revenue-detailed'
      path: '/reports/income-statement/revenue-detailed'
      fullPath: '/reports/income-statement/revenue-detailed'
      preLoaderRoute: typeof AuthenticatedReportsIncomeStatementRevenueDetailedImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/roles/$roleId/edit': {
      id: '/_authenticated/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/roles/$roleId/edit'
      preLoaderRoute: typeof AuthenticatedRolesRoleIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/services/$serviceId/edit': {
      id: '/_authenticated/services/$serviceId/edit'
      path: '/services/$serviceId/edit'
      fullPath: '/services/$serviceId/edit'
      preLoaderRoute: typeof AuthenticatedServicesServiceIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/users/$userId/edit': {
      id: '/_authenticated/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedUsersUserIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/invoices/payments/': {
      id: '/_authenticated/invoices/payments/'
      path: '/invoices/payments'
      fullPath: '/invoices/payments'
      preLoaderRoute: typeof AuthenticatedInvoicesPaymentsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/reports/income-statement/': {
      id: '/_authenticated/reports/income-statement/'
      path: '/reports/income-statement'
      fullPath: '/reports/income-statement'
      preLoaderRoute: typeof AuthenticatedReportsIncomeStatementIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/invoices/payments/$paymentId/edit': {
      id: '/_authenticated/invoices/payments/$paymentId/edit'
      path: '/invoices/payments/$paymentId/edit'
      fullPath: '/invoices/payments/$paymentId/edit'
      preLoaderRoute: typeof AuthenticatedInvoicesPaymentsPaymentIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authForgotPasswordResetCodeRoute: typeof authForgotPasswordResetCodeRoute
  authForgotPasswordIndexRoute: typeof authForgotPasswordIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authForgotPasswordResetCodeRoute: authForgotPasswordResetCodeRoute,
  authForgotPasswordIndexRoute: authForgotPasswordIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedChartOfAccountsNewRoute: typeof AuthenticatedChartOfAccountsNewRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedExpensesNewRoute: typeof AuthenticatedExpensesNewRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedProfilePasswordRoute: typeof AuthenticatedProfilePasswordRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedReportsClientStatementRoute: typeof AuthenticatedReportsClientStatementRoute
  AuthenticatedReportsCollectedPaymentsRoute: typeof AuthenticatedReportsCollectedPaymentsRoute
  AuthenticatedReportsExpensesReportRoute: typeof AuthenticatedReportsExpensesReportRoute
  AuthenticatedReportsInvoiceStatusRoute: typeof AuthenticatedReportsInvoiceStatusRoute
  AuthenticatedReportsOutstandingInvoicesRoute: typeof AuthenticatedReportsOutstandingInvoicesRoute
  AuthenticatedRolesNewRoute: typeof AuthenticatedRolesNewRoute
  AuthenticatedServicesNewRoute: typeof AuthenticatedServicesNewRoute
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedChartOfAccountsIndexRoute: typeof AuthenticatedChartOfAccountsIndexRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedExpensesIndexRoute: typeof AuthenticatedExpensesIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedJournalEntriesIndexRoute: typeof AuthenticatedJournalEntriesIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedServicesIndexRoute: typeof AuthenticatedServicesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedChartOfAccountsAccountIdEditRoute: typeof AuthenticatedChartOfAccountsAccountIdEditRoute
  AuthenticatedClientsClientIdEditRoute: typeof AuthenticatedClientsClientIdEditRoute
  AuthenticatedExpensesExpenseIdEditRoute: typeof AuthenticatedExpensesExpenseIdEditRoute
  AuthenticatedInvoicesInvoiceIdEditRoute: typeof AuthenticatedInvoicesInvoiceIdEditRoute
  AuthenticatedInvoicesInvoiceIdPrintRoute: typeof AuthenticatedInvoicesInvoiceIdPrintRoute
  AuthenticatedInvoicesPaymentsNewRoute: typeof AuthenticatedInvoicesPaymentsNewRoute
  AuthenticatedProjectsProjectIdEditRoute: typeof AuthenticatedProjectsProjectIdEditRoute
  AuthenticatedReportsIncomeStatementExpenseDetailedRoute: typeof AuthenticatedReportsIncomeStatementExpenseDetailedRoute
  AuthenticatedReportsIncomeStatementRevenueDetailedRoute: typeof AuthenticatedReportsIncomeStatementRevenueDetailedRoute
  AuthenticatedRolesRoleIdEditRoute: typeof AuthenticatedRolesRoleIdEditRoute
  AuthenticatedServicesServiceIdEditRoute: typeof AuthenticatedServicesServiceIdEditRoute
  AuthenticatedUsersUserIdEditRoute: typeof AuthenticatedUsersUserIdEditRoute
  AuthenticatedInvoicesPaymentsIndexRoute: typeof AuthenticatedInvoicesPaymentsIndexRoute
  AuthenticatedReportsIncomeStatementIndexRoute: typeof AuthenticatedReportsIncomeStatementIndexRoute
  AuthenticatedInvoicesPaymentsPaymentIdEditRoute: typeof AuthenticatedInvoicesPaymentsPaymentIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedChartOfAccountsNewRoute: AuthenticatedChartOfAccountsNewRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedExpensesNewRoute: AuthenticatedExpensesNewRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedProfilePasswordRoute: AuthenticatedProfilePasswordRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedReportsClientStatementRoute:
    AuthenticatedReportsClientStatementRoute,
  AuthenticatedReportsCollectedPaymentsRoute:
    AuthenticatedReportsCollectedPaymentsRoute,
  AuthenticatedReportsExpensesReportRoute:
    AuthenticatedReportsExpensesReportRoute,
  AuthenticatedReportsInvoiceStatusRoute:
    AuthenticatedReportsInvoiceStatusRoute,
  AuthenticatedReportsOutstandingInvoicesRoute:
    AuthenticatedReportsOutstandingInvoicesRoute,
  AuthenticatedRolesNewRoute: AuthenticatedRolesNewRoute,
  AuthenticatedServicesNewRoute: AuthenticatedServicesNewRoute,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedChartOfAccountsIndexRoute:
    AuthenticatedChartOfAccountsIndexRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedExpensesIndexRoute: AuthenticatedExpensesIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedJournalEntriesIndexRoute: AuthenticatedJournalEntriesIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedServicesIndexRoute: AuthenticatedServicesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedChartOfAccountsAccountIdEditRoute:
    AuthenticatedChartOfAccountsAccountIdEditRoute,
  AuthenticatedClientsClientIdEditRoute: AuthenticatedClientsClientIdEditRoute,
  AuthenticatedExpensesExpenseIdEditRoute:
    AuthenticatedExpensesExpenseIdEditRoute,
  AuthenticatedInvoicesInvoiceIdEditRoute:
    AuthenticatedInvoicesInvoiceIdEditRoute,
  AuthenticatedInvoicesInvoiceIdPrintRoute:
    AuthenticatedInvoicesInvoiceIdPrintRoute,
  AuthenticatedInvoicesPaymentsNewRoute: AuthenticatedInvoicesPaymentsNewRoute,
  AuthenticatedProjectsProjectIdEditRoute:
    AuthenticatedProjectsProjectIdEditRoute,
  AuthenticatedReportsIncomeStatementExpenseDetailedRoute:
    AuthenticatedReportsIncomeStatementExpenseDetailedRoute,
  AuthenticatedReportsIncomeStatementRevenueDetailedRoute:
    AuthenticatedReportsIncomeStatementRevenueDetailedRoute,
  AuthenticatedRolesRoleIdEditRoute: AuthenticatedRolesRoleIdEditRoute,
  AuthenticatedServicesServiceIdEditRoute:
    AuthenticatedServicesServiceIdEditRoute,
  AuthenticatedUsersUserIdEditRoute: AuthenticatedUsersUserIdEditRoute,
  AuthenticatedInvoicesPaymentsIndexRoute:
    AuthenticatedInvoicesPaymentsIndexRoute,
  AuthenticatedReportsIncomeStatementIndexRoute:
    AuthenticatedReportsIncomeStatementIndexRoute,
  AuthenticatedInvoicesPaymentsPaymentIdEditRoute:
    AuthenticatedInvoicesPaymentsPaymentIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authRouteRouteWithChildren
  '': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forgot-password/reset-code': typeof authForgotPasswordResetCodeRoute
  '/chart-of-accounts/new': typeof AuthenticatedChartOfAccountsNewRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/profile/password': typeof AuthenticatedProfilePasswordRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/reports/client-statement': typeof AuthenticatedReportsClientStatementRoute
  '/reports/collected-payments': typeof AuthenticatedReportsCollectedPaymentsRoute
  '/reports/expenses-report': typeof AuthenticatedReportsExpensesReportRoute
  '/reports/invoice-status': typeof AuthenticatedReportsInvoiceStatusRoute
  '/reports/outstanding-invoices': typeof AuthenticatedReportsOutstandingInvoicesRoute
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/services/new': typeof AuthenticatedServicesNewRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/chart-of-accounts': typeof AuthenticatedChartOfAccountsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/journal-entries': typeof AuthenticatedJournalEntriesIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/chart-of-accounts/$accountId/edit': typeof AuthenticatedChartOfAccountsAccountIdEditRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/expenses/$expenseId/edit': typeof AuthenticatedExpensesExpenseIdEditRoute
  '/invoices/$invoiceId/edit': typeof AuthenticatedInvoicesInvoiceIdEditRoute
  '/invoices/$invoiceId/print': typeof AuthenticatedInvoicesInvoiceIdPrintRoute
  '/invoices/payments/new': typeof AuthenticatedInvoicesPaymentsNewRoute
  '/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditRoute
  '/reports/income-statement/expense-detailed': typeof AuthenticatedReportsIncomeStatementExpenseDetailedRoute
  '/reports/income-statement/revenue-detailed': typeof AuthenticatedReportsIncomeStatementRevenueDetailedRoute
  '/roles/$roleId/edit': typeof AuthenticatedRolesRoleIdEditRoute
  '/services/$serviceId/edit': typeof AuthenticatedServicesServiceIdEditRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/invoices/payments': typeof AuthenticatedInvoicesPaymentsIndexRoute
  '/reports/income-statement': typeof AuthenticatedReportsIncomeStatementIndexRoute
  '/invoices/payments/$paymentId/edit': typeof AuthenticatedInvoicesPaymentsPaymentIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof authRouteRouteWithChildren
  '': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof authLoginRoute
  '/reset-password': typeof authResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/forgot-password/reset-code': typeof authForgotPasswordResetCodeRoute
  '/chart-of-accounts/new': typeof AuthenticatedChartOfAccountsNewRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/profile/password': typeof AuthenticatedProfilePasswordRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/reports/client-statement': typeof AuthenticatedReportsClientStatementRoute
  '/reports/collected-payments': typeof AuthenticatedReportsCollectedPaymentsRoute
  '/reports/expenses-report': typeof AuthenticatedReportsExpensesReportRoute
  '/reports/invoice-status': typeof AuthenticatedReportsInvoiceStatusRoute
  '/reports/outstanding-invoices': typeof AuthenticatedReportsOutstandingInvoicesRoute
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/services/new': typeof AuthenticatedServicesNewRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/forgot-password': typeof authForgotPasswordIndexRoute
  '/chart-of-accounts': typeof AuthenticatedChartOfAccountsIndexRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/expenses': typeof AuthenticatedExpensesIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/journal-entries': typeof AuthenticatedJournalEntriesIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/services': typeof AuthenticatedServicesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/chart-of-accounts/$accountId/edit': typeof AuthenticatedChartOfAccountsAccountIdEditRoute
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/expenses/$expenseId/edit': typeof AuthenticatedExpensesExpenseIdEditRoute
  '/invoices/$invoiceId/edit': typeof AuthenticatedInvoicesInvoiceIdEditRoute
  '/invoices/$invoiceId/print': typeof AuthenticatedInvoicesInvoiceIdPrintRoute
  '/invoices/payments/new': typeof AuthenticatedInvoicesPaymentsNewRoute
  '/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditRoute
  '/reports/income-statement/expense-detailed': typeof AuthenticatedReportsIncomeStatementExpenseDetailedRoute
  '/reports/income-statement/revenue-detailed': typeof AuthenticatedReportsIncomeStatementRevenueDetailedRoute
  '/roles/$roleId/edit': typeof AuthenticatedRolesRoleIdEditRoute
  '/services/$serviceId/edit': typeof AuthenticatedServicesServiceIdEditRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/invoices/payments': typeof AuthenticatedInvoicesPaymentsIndexRoute
  '/reports/income-statement': typeof AuthenticatedReportsIncomeStatementIndexRoute
  '/invoices/payments/$paymentId/edit': typeof AuthenticatedInvoicesPaymentsPaymentIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/(auth)/forgot-password/reset-code': typeof authForgotPasswordResetCodeRoute
  '/_authenticated/chart-of-accounts/new': typeof AuthenticatedChartOfAccountsNewRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/expenses/new': typeof AuthenticatedExpensesNewRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/profile/password': typeof AuthenticatedProfilePasswordRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/reports/client-statement': typeof AuthenticatedReportsClientStatementRoute
  '/_authenticated/reports/collected-payments': typeof AuthenticatedReportsCollectedPaymentsRoute
  '/_authenticated/reports/expenses-report': typeof AuthenticatedReportsExpensesReportRoute
  '/_authenticated/reports/invoice-status': typeof AuthenticatedReportsInvoiceStatusRoute
  '/_authenticated/reports/outstanding-invoices': typeof AuthenticatedReportsOutstandingInvoicesRoute
  '/_authenticated/roles/new': typeof AuthenticatedRolesNewRoute
  '/_authenticated/services/new': typeof AuthenticatedServicesNewRoute
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/(auth)/forgot-password/': typeof authForgotPasswordIndexRoute
  '/_authenticated/chart-of-accounts/': typeof AuthenticatedChartOfAccountsIndexRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/expenses/': typeof AuthenticatedExpensesIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/journal-entries/': typeof AuthenticatedJournalEntriesIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/services/': typeof AuthenticatedServicesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/chart-of-accounts/$accountId/edit': typeof AuthenticatedChartOfAccountsAccountIdEditRoute
  '/_authenticated/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute
  '/_authenticated/expenses/$expenseId/edit': typeof AuthenticatedExpensesExpenseIdEditRoute
  '/_authenticated/invoices/$invoiceId/edit': typeof AuthenticatedInvoicesInvoiceIdEditRoute
  '/_authenticated/invoices/$invoiceId/print': typeof AuthenticatedInvoicesInvoiceIdPrintRoute
  '/_authenticated/invoices/payments/new': typeof AuthenticatedInvoicesPaymentsNewRoute
  '/_authenticated/projects/$projectId/edit': typeof AuthenticatedProjectsProjectIdEditRoute
  '/_authenticated/reports/income-statement/expense-detailed': typeof AuthenticatedReportsIncomeStatementExpenseDetailedRoute
  '/_authenticated/reports/income-statement/revenue-detailed': typeof AuthenticatedReportsIncomeStatementRevenueDetailedRoute
  '/_authenticated/roles/$roleId/edit': typeof AuthenticatedRolesRoleIdEditRoute
  '/_authenticated/services/$serviceId/edit': typeof AuthenticatedServicesServiceIdEditRoute
  '/_authenticated/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/_authenticated/invoices/payments/': typeof AuthenticatedInvoicesPaymentsIndexRoute
  '/_authenticated/reports/income-statement/': typeof AuthenticatedReportsIncomeStatementIndexRoute
  '/_authenticated/invoices/payments/$paymentId/edit': typeof AuthenticatedInvoicesPaymentsPaymentIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/change-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/forgot-password/reset-code'
    | '/chart-of-accounts/new'
    | '/clients/new'
    | '/expenses/new'
    | '/invoices/new'
    | '/profile/password'
    | '/projects/new'
    | '/reports/client-statement'
    | '/reports/collected-payments'
    | '/reports/expenses-report'
    | '/reports/invoice-status'
    | '/reports/outstanding-invoices'
    | '/roles/new'
    | '/services/new'
    | '/users/new'
    | '/forgot-password'
    | '/chart-of-accounts'
    | '/clients'
    | '/expenses'
    | '/invoices'
    | '/journal-entries'
    | '/projects'
    | '/roles'
    | '/services'
    | '/users'
    | '/chart-of-accounts/$accountId/edit'
    | '/clients/$clientId/edit'
    | '/expenses/$expenseId/edit'
    | '/invoices/$invoiceId/edit'
    | '/invoices/$invoiceId/print'
    | '/invoices/payments/new'
    | '/projects/$projectId/edit'
    | '/reports/income-statement/expense-detailed'
    | '/reports/income-statement/revenue-detailed'
    | '/roles/$roleId/edit'
    | '/services/$serviceId/edit'
    | '/users/$userId/edit'
    | '/invoices/payments'
    | '/reports/income-statement'
    | '/invoices/payments/$paymentId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/change-password'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/forgot-password/reset-code'
    | '/chart-of-accounts/new'
    | '/clients/new'
    | '/expenses/new'
    | '/invoices/new'
    | '/profile/password'
    | '/projects/new'
    | '/reports/client-statement'
    | '/reports/collected-payments'
    | '/reports/expenses-report'
    | '/reports/invoice-status'
    | '/reports/outstanding-invoices'
    | '/roles/new'
    | '/services/new'
    | '/users/new'
    | '/forgot-password'
    | '/chart-of-accounts'
    | '/clients'
    | '/expenses'
    | '/invoices'
    | '/journal-entries'
    | '/projects'
    | '/roles'
    | '/services'
    | '/users'
    | '/chart-of-accounts/$accountId/edit'
    | '/clients/$clientId/edit'
    | '/expenses/$expenseId/edit'
    | '/invoices/$invoiceId/edit'
    | '/invoices/$invoiceId/print'
    | '/invoices/payments/new'
    | '/projects/$projectId/edit'
    | '/reports/income-statement/expense-detailed'
    | '/reports/income-statement/revenue-detailed'
    | '/roles/$roleId/edit'
    | '/services/$serviceId/edit'
    | '/users/$userId/edit'
    | '/invoices/payments'
    | '/reports/income-statement'
    | '/invoices/payments/$paymentId/edit'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_authenticated'
    | '/change-password'
    | '/(auth)/login'
    | '/(auth)/reset-password'
    | '/_authenticated/dashboard'
    | '/(auth)/forgot-password/reset-code'
    | '/_authenticated/chart-of-accounts/new'
    | '/_authenticated/clients/new'
    | '/_authenticated/expenses/new'
    | '/_authenticated/invoices/new'
    | '/_authenticated/profile/password'
    | '/_authenticated/projects/new'
    | '/_authenticated/reports/client-statement'
    | '/_authenticated/reports/collected-payments'
    | '/_authenticated/reports/expenses-report'
    | '/_authenticated/reports/invoice-status'
    | '/_authenticated/reports/outstanding-invoices'
    | '/_authenticated/roles/new'
    | '/_authenticated/services/new'
    | '/_authenticated/users/new'
    | '/(auth)/forgot-password/'
    | '/_authenticated/chart-of-accounts/'
    | '/_authenticated/clients/'
    | '/_authenticated/expenses/'
    | '/_authenticated/invoices/'
    | '/_authenticated/journal-entries/'
    | '/_authenticated/projects/'
    | '/_authenticated/roles/'
    | '/_authenticated/services/'
    | '/_authenticated/users/'
    | '/_authenticated/chart-of-accounts/$accountId/edit'
    | '/_authenticated/clients/$clientId/edit'
    | '/_authenticated/expenses/$expenseId/edit'
    | '/_authenticated/invoices/$invoiceId/edit'
    | '/_authenticated/invoices/$invoiceId/print'
    | '/_authenticated/invoices/payments/new'
    | '/_authenticated/projects/$projectId/edit'
    | '/_authenticated/reports/income-statement/expense-detailed'
    | '/_authenticated/reports/income-statement/revenue-detailed'
    | '/_authenticated/roles/$roleId/edit'
    | '/_authenticated/services/$serviceId/edit'
    | '/_authenticated/users/$userId/edit'
    | '/_authenticated/invoices/payments/'
    | '/_authenticated/reports/income-statement/'
    | '/_authenticated/invoices/payments/$paymentId/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)",
        "/_authenticated",
        "/change-password"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)": {
      "filePath": "(auth)/route.tsx",
      "children": [
        "/(auth)/login",
        "/(auth)/reset-password",
        "/(auth)/forgot-password/reset-code",
        "/(auth)/forgot-password/"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/dashboard",
        "/_authenticated/chart-of-accounts/new",
        "/_authenticated/clients/new",
        "/_authenticated/expenses/new",
        "/_authenticated/invoices/new",
        "/_authenticated/profile/password",
        "/_authenticated/projects/new",
        "/_authenticated/reports/client-statement",
        "/_authenticated/reports/collected-payments",
        "/_authenticated/reports/expenses-report",
        "/_authenticated/reports/invoice-status",
        "/_authenticated/reports/outstanding-invoices",
        "/_authenticated/roles/new",
        "/_authenticated/services/new",
        "/_authenticated/users/new",
        "/_authenticated/chart-of-accounts/",
        "/_authenticated/clients/",
        "/_authenticated/expenses/",
        "/_authenticated/invoices/",
        "/_authenticated/journal-entries/",
        "/_authenticated/projects/",
        "/_authenticated/roles/",
        "/_authenticated/services/",
        "/_authenticated/users/",
        "/_authenticated/chart-of-accounts/$accountId/edit",
        "/_authenticated/clients/$clientId/edit",
        "/_authenticated/expenses/$expenseId/edit",
        "/_authenticated/invoices/$invoiceId/edit",
        "/_authenticated/invoices/$invoiceId/print",
        "/_authenticated/invoices/payments/new",
        "/_authenticated/projects/$projectId/edit",
        "/_authenticated/reports/income-statement/expense-detailed",
        "/_authenticated/reports/income-statement/revenue-detailed",
        "/_authenticated/roles/$roleId/edit",
        "/_authenticated/services/$serviceId/edit",
        "/_authenticated/users/$userId/edit",
        "/_authenticated/invoices/payments/",
        "/_authenticated/reports/income-statement/",
        "/_authenticated/invoices/payments/$paymentId/edit"
      ]
    },
    "/change-password": {
      "filePath": "change-password.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx",
      "parent": "/(auth)"
    },
    "/(auth)/reset-password": {
      "filePath": "(auth)/reset-password.tsx",
      "parent": "/(auth)"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/(auth)/forgot-password/reset-code": {
      "filePath": "(auth)/forgot-password/reset-code.tsx",
      "parent": "/(auth)"
    },
    "/_authenticated/chart-of-accounts/new": {
      "filePath": "_authenticated/chart-of-accounts/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/clients/new": {
      "filePath": "_authenticated/clients/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/expenses/new": {
      "filePath": "_authenticated/expenses/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/invoices/new": {
      "filePath": "_authenticated/invoices/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile/password": {
      "filePath": "_authenticated/profile/password.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/projects/new": {
      "filePath": "_authenticated/projects/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/reports/client-statement": {
      "filePath": "_authenticated/reports/client-statement.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/reports/collected-payments": {
      "filePath": "_authenticated/reports/collected-payments.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/reports/expenses-report": {
      "filePath": "_authenticated/reports/expenses-report.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/reports/invoice-status": {
      "filePath": "_authenticated/reports/invoice-status.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/reports/outstanding-invoices": {
      "filePath": "_authenticated/reports/outstanding-invoices.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/roles/new": {
      "filePath": "_authenticated/roles/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/services/new": {
      "filePath": "_authenticated/services/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/new": {
      "filePath": "_authenticated/users/new.tsx",
      "parent": "/_authenticated"
    },
    "/(auth)/forgot-password/": {
      "filePath": "(auth)/forgot-password/index.tsx",
      "parent": "/(auth)"
    },
    "/_authenticated/chart-of-accounts/": {
      "filePath": "_authenticated/chart-of-accounts/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/clients/": {
      "filePath": "_authenticated/clients/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/expenses/": {
      "filePath": "_authenticated/expenses/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/invoices/": {
      "filePath": "_authenticated/invoices/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/journal-entries/": {
      "filePath": "_authenticated/journal-entries/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/projects/": {
      "filePath": "_authenticated/projects/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/roles/": {
      "filePath": "_authenticated/roles/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/services/": {
      "filePath": "_authenticated/services/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/": {
      "filePath": "_authenticated/users/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/chart-of-accounts/$accountId/edit": {
      "filePath": "_authenticated/chart-of-accounts/$accountId.edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/clients/$clientId/edit": {
      "filePath": "_authenticated/clients/$clientId.edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/expenses/$expenseId/edit": {
      "filePath": "_authenticated/expenses/$expenseId.edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/invoices/$invoiceId/edit": {
      "filePath": "_authenticated/invoices/$invoiceId.edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/invoices/$invoiceId/print": {
      "filePath": "_authenticated/invoices/$invoiceId.print.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/invoices/payments/new": {
      "filePath": "_authenticated/invoices/payments/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/projects/$projectId/edit": {
      "filePath": "_authenticated/projects/$projectId.edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/reports/income-statement/expense-detailed": {
      "filePath": "_authenticated/reports/income-statement/expense-detailed.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/reports/income-statement/revenue-detailed": {
      "filePath": "_authenticated/reports/income-statement/revenue-detailed.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/roles/$roleId/edit": {
      "filePath": "_authenticated/roles/$roleId.edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/services/$serviceId/edit": {
      "filePath": "_authenticated/services/$serviceId.edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/users/$userId/edit": {
      "filePath": "_authenticated/users/$userId.edit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/invoices/payments/": {
      "filePath": "_authenticated/invoices/payments/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/reports/income-statement/": {
      "filePath": "_authenticated/reports/income-statement/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/invoices/payments/$paymentId/edit": {
      "filePath": "_authenticated/invoices/payments/$paymentId.edit.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
